# Generated by Django 6.0.3 on 2026-03-06 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CLO-1', max_length=20)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., PLO-1', max_length=20)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='curriculum.program')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('program', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ObjectiveAlignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.courseobjective')),
                ('program_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.programobjective')),
            ],
            options={
                'unique_together': {('course_objective', 'program_objective')},
            },
        ),
        migrations.AddField(
            model_name='courseobjective',
            name='program_objectives',
            field=models.ManyToManyField(blank=True, related_name='course_objectives', through='curriculum.ObjectiveAlignment', to='curriculum.programobjective'),
        ),
        migrations.AlterUniqueTogether(
            name='courseobjective',
            unique_together={('course', 'code')},
        ),
    ]
