# Generated by Django 6.0.3 on 2026-03-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_token',
            field=models.UUIDField(blank=True, help_text='Token for registration-link auto-enrollment', null=True, unique=True),
        ),
    ]
